export { default as IconAttach } from './attach'
export { default as IconDelete } from './delete'
export { default as IconMicOff } from './mic-off'
export { default as IconMicOn } from './mic-on'
export { default as IconPause } from './pause'
export { default as IconPlay } from './play'
export { default as IconSend } from './send'
