import type { Types } from '@wezard/halo-core'

export const mockedChat: {
  chatUser: Types.UserDetails
  users: Types.UserDetails[]
  messages: Types.MessageType.Any[]
} = {
  chatUser: {
    id: 'user1',
    firstName: 'Giorgia',
    lastName: 'DeLonghi',
    image: 'https://i.pravatar.cc/150?img=13',
    nickname: 'giogia',
  },
  users: [
    {
      id: 'user1',
      firstName: 'Giorgia',
      lastName: 'DeLonghi',
      image: 'https://i.pravatar.cc/150?img=13',
      nickname: 'giogia',
    },
    {
      id: 'user2',
      firstName: 'Paolo Federico',
      lastName: 'Morelli',
      image: 'https://i.pravatar.cc/150?img=3',
      nickname: 'paul',
    },
  ],
  messages: [
    {
      id: 'message1',
      contentType: 'TEXT',
      createdAt: '2023-03-20T09:00:00.000Z',
      updatedAt: '2023-03-20T09:00:00.000Z',
      createdBy: 'user1',
      deleted: false,
      delivered: true,
      metadata: null,
      readBy: [],
      room: 'room1',
      text: 'Ciao! Sì, mi piacerebbe un sacco! Dove e a che ora?',
    },
    {
      id: 'message2',
      contentType: 'TEXT',
      createdAt: '2023-03-16T09:12:00.000Z',
      updatedAt: '2023-03-16T09:12:00.000Z',
      createdBy: 'user2',
      deleted: false,
      delivered: true,
      metadata: null,
      readBy: [],
      room: 'room1',
      text: 'Ciao, stasera pensavo di organizzare una partitella di calcetto. Sei interessato?',
    },
    {
      id: 'message3',
      contentType: 'TEXT',
      createdAt: '2023-03-22T09:13:40.000Z',
      updatedAt: '2023-03-22T09:13:40.000Z',
      createdBy: 'user2',
      deleted: false,
      delivered: true,
      metadata: null,
      readBy: [],
      room: 'room1',
      text: 'Bene! Direi alle 20 al campo di calcetto vicino al parco. Ti va bene?',
    },

    {
      id: 'message5',
      contentType: 'TEXT',
      createdAt: '2023-03-23T09:08:40.000Z',
      updatedAt: '2023-03-23T09:08:40.000Z',
      createdBy: 'user1',
      deleted: false,
      delivered: true,
      metadata: null,
      readBy: [],
      room: 'room1',
      text: 'Perfetto! Ma sai che io tifo per il Galatasaray, giusto?',
    },
    {
      id: 'message4',
      contentType: 'TEXT',
      createdAt: '2023-03-23T09:09:00.000Z',
      updatedAt: '2023-03-23T09:09:00.000Z',
      createdBy: 'user2',
      deleted: false,
      delivered: true,
      metadata: null,
      readBy: [],
      room: 'room1',
      text: "Ah sì? Non lo sapevo! Ma non importa, l'importante è divertirsi e giocare insieme!",
    },

    {
      id: 'message6',
      contentType: 'TEXT',
      createdAt: '2023-03-23T09:09:10.000Z',
      updatedAt: '2023-03-23T09:09:10.000Z',
      createdBy: 'user1',
      deleted: false,
      delivered: true,
      metadata: null,
      readBy: [],
      room: 'room1',
      text: "Esatto! E poi, magari se ci mettiamo d'accordo possiamo anche fare una partitella Galatasaray contro il resto del mondo! ;)",
    },
    {
      id: 'message7',
      contentType: 'TEXT',
      createdAt: '2023-03-23T09:09:53.000Z',
      updatedAt: '2023-03-23T09:09:53.000Z',
      createdBy: 'user2',
      deleted: false,
      delivered: true,
      metadata: null,
      readBy: [],
      room: 'room1',
      text: 'Ahahah! Ci sta! Ma stai tranquillo, non ti faremo troppo male!',
    },
    {
      id: 'message8',
      contentType: 'TEXT',
      createdAt: '2023-03-23T09:09:59.000Z',
      updatedAt: '2023-03-23T09:09:59.000Z',
      createdBy: 'user1',
      deleted: false,
      delivered: true,
      metadata: null,
      readBy: [],
      room: 'room1',
      text: 'Ahahah! Grazie! Allora ci vediamo stasera alle 20!',
    },
  ],
}
